version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    # environment:
    #   RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    #   RABBITMQ_DEFAULT_USER: "admin"
    #   RABBITMQ_DEFAULT_PASS: "admin"
    ports:
      - "15672:15672" # interfaz grafica de rabbitmq
      - "5672:5672" # permite que las aplicaciones envien mensajes a traves de este puerto
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: on-failure
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge
